version: '3.9'

services:
  db:
    image: mongo:7.0
    restart: always
    env_file:
      - ./config/mongo.env
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - auth.local

  grpc:
    image: auth:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - ./config/auth.env
    ports:
      - 50051:50051
    networks:
      - auth.local
    
volumes:
  mongodata:
    driver: local

networks:
  auth.local: